### PR TITLE
Update gems for cocoapods-trunk

### PR DESCRIPTION
**Pull request by dnkoutso**

### CODE REVIEW

**Comment by dnkoutso** [comment]
One sec

**Comment by orta** [comment]
such time

**Comment by dnkoutso** [comment]
Yes.....travis is taking its sweet little time...

**Comment by dnkoutso** [comment]
lol I dont think it will start...

**Comment by orta** [comment]
hah no - let's try restarting it

**Comment by dnkoutso** [comment]
wow it finally ran but it's red. Looking.

**Comment by dnkoutso** [comment]
updated travis config to match the rest. PTAL

**Comment by macteo** [comment]
I'm seen really long delays on travis recently for open source projects. 
Unfortunately it failed three times.

**Comment by dnkoutso** [comment]
This is a valid faliure now, I can repro. Will take care of it tomorrow.

**Comment by dnkoutso** [comment]
looking now.

**Comment by dnkoutso** [comment]
I think this should do it

**Comment by dnkoutso** [comment]
@orta whoooohoooo green!

**Comment by orta** [comment]
Awesome

**Pull request merged**
