### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jasl**
- Loosen netrc requirements as #94 does
- Update development dependencies for better support MRI 2.3+

### CODE REVIEW

**Comment by jasl** [comment]
cocoapods-trunk pinned netrc against 0.7.8 at [51aa6a5](https://github.com/CocoaPods/cocoapods-trunk/commit/51aa6a5e3ac66082445540af85d946a6515fa9c4), due to netrc 0.7.9 reverted the change, cocoapods-trunk revert 51aa6a5 changes and loosen requirements of netrc is better, that makes less dependencies conflict when using bundler.

in addition, webmock 1.2 doesn't support Ruby 2.3+, I also upgrade development dependencies and refactor test cases.

**Comment by jasl** [comment]
@segiddins sorry for trouble you, is there any update?

**Comment by segiddins** [comment]
I'm on vacation at the moment, I'll try to take a look when I get home

**Comment by jasl** [comment]
ping @segiddins

**Comment by segiddins** [comment]
@DanToml want to look at this?

**Comment by jasl** [comment]
@DanToml Could you bump the version?

**Comment by DanToml** [comment]
@jasl I can't do a release today, but you should be able to point this repo at master (or the specific merged sha) in your Gemfile in the meantime.

**Comment by danielkiedrowski** [comment]
Any updates on that? Using the current master crashes at my machine.

**Comment by jasl** [comment]
@danielkiedrowski 
what output? and your `ruby -v`

**Comment by danielkiedrowski** [comment]
@jasl

`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

And thats what happens when I do `pod install`.

### Command

```
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin/pod install
```

### Report

* What did you do?

Run `pod install`

* What did you expect to happen?

Installing pods.

* What happened instead?

I got this output.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/kie/.rbenv/versions/2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9bd66c0681c601bf1c4e124736e47752102b1e72
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

pod 'JLRoutes', '~> 2.0'
pod 'SwiftyJSON', '~> 3.1'
pod 'GooglePlacesAutocomplete', :git => 'git@github.com:danielkiedrowski/ios_google_places_autocomplete.git'
pod 'MMMaterialDesignSpinner', '~> 0.2'
pod 'RSKImageCropper', '~> 1.1'
pod 'CocoaSecurity', '~> 1.2'
pod 'GoogleAnalytics', '~> 3.17' 
pod 'FBSDKCoreKit', '~> 4.24'
pod 'FBSDKLoginKit', '~> 4.24'
pod 'INTULocationManager', '~> 4.2'
pod 'SDWebImage', '~> 4.0'
pod 'Alamofire', '~> 4.0'
pod 'MXLCalendarManager', '~> 1.0.4'
pod 'TTTAttributedLabel', '~> 2.0'
pod 'KMPlaceholderTextView', '~> 1.3'
pod 'Intercom', '~> 3.2'
pod 'BadgeSwift', '~> 3.0'
pod 'Toast-Swift', '~> 2.0'
pod 'Zip', '~> 0.6'
pod 'JTAppleCalendar', '7.0.1' # fixed version, since 7.0.5 broke the selection
pod 'Stripe', '~> 11.0'
pod 'UIScrollView-InfiniteScroll', '~> 1.0'

target 'YouPooly'
target 'YouPoolyDev'
target 'YouPoolyTests'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
NoMethodError - undefined method `script_phases' for #<Pod::Podfile::TargetDefinition label=Pods-YouPooly>
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:269:in `update_target_script_phases'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:167:in `block in integrate!'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:159:in `integrate!'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer.rb:564:in `block in integrate_user_project'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer.rb:561:in `integrate_user_project'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/installer.rb:121:in `install!'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/command/install.rb:41:in `run'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/lib/cocoapods/command.rb:52:in `run'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/CocoaPods-0fcf5944e47c/bin/pod:55:in `<top (required)>'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin/pod:22:in `load'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin/pod:22:in `<top (required)>'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/kie/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/Users/kie/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/kie/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
```

**Comment by jasl** [comment]
@danielkiedrowski 
I think this not relate to cocoapods-trunk.

**Comment by danielkiedrowski** [comment]
@jasl 

Thank you for the quick reply. I don't know about the internal dependencies of the cocoapods ecosystem, but I know that this crash came up as soon as I added this to my Gemfile:

```
gem 'cocoapods-trunk', :git => 'git://github.com/CocoaPods/cocoapods-trunk.git'
gem 'cocoapods', :git => 'git://github.com/CocoaPods/CocoaPods.git'
```

Do you have idea how I can resolve this, or how I can debug it?

Thank you again.

**Comment by jasl** [comment]
@danielkiedrowski 
have you tried use release version of cocoapods?

```ruby
gem 'cocoapods-trunk', :git => 'git://github.com/CocoaPods/cocoapods-trunk.git'
gem 'cocoapods'
```

The error you've  met

`NoMethodError - undefined method `script_phases' for #<Pod::Podfile::TargetDefinition label=Pods-YouPooly>`

means there is no method called `script_phases` in class `Pod::Podfile::TargetDefinition`, that actually not exists in release version according to <http://www.rubydoc.info/github/CocoaPods/Core/master/Pod/Podfile/TargetDefinition>

Accroding to <https://github.com/CocoaPods/Core/blob/master/CHANGELOG.md>

```
Master

Enhancements

...

Add Podfile DSL for script_phase
Dimitris Koutsogiorgas #389

...
```

I think this may a unstable feature of cocoapods-core, and maybe you can create a issue for them to get an answer

**Pull request merged**
