### PR TITLE
[Push] Propagate --allow-warnings to the trunk server

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/CocoaPods/issues/3855.

### CODE REVIEW

**Comment by segiddins** [comment]
\c @orta @alloy

**Comment by alloy** [comment]
Beauty :+1:

**Comment by jiisd** [comment]
now I have a problem like this when i checking a file ,what should i do？ thanks.
 -> YHAutoCoding (1.0.0)
    - WARN  |  YHAutoCoding/YHAutoCoding/NSObject+YHAutoCoding.m:12:17: warning: method definition for 'ignoredMemberNames' not found [-Wincomplete-implementation]
    - NOTE  |  YHAutoCoding/YHAutoCoding/NSObject+YHAutoCoding.h:14:1: note: method 'ignoredMemberNames' declared here

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it).

**Comment by orta** [comment]
You can either fix the objective-c warning that you are seeing, or use  ` --allow-warnings` in your `pod trunk push` to ignore the warning

**Comment by jiisd** [comment]
Successed! Thank you.

**Pull request merged**
